### ISSUE TITLE
Open source mobile apps or server-side code

### ISSUE THREAD

**Issue by TosotadaThrone** [Pocket/extension-save-to-pocket#121] opened 2019-08-26 21:08 UTC
When you will open source the android app (or other apps) or server-side code?

Sorry for my english.

**Comment by anthony-liddle** [comment] 2021-11-30 18:38
Closing this as a duplicate of https://github.com/Pocket/extension-save-to-pocket/issues/75

**Closed by anthony-liddle** 2021-11-30 18:38 UTC
Labels: duplicate
